steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA',
      '-f',
      '${_DOCKERFILE_PATH}',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA'
    ]

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'run',
      'deploy',
      '${_SERVICE_NAME}',
      '--image',
      'gcr.io/${_PROJECT_ID}/${_SERVICE_NAME}:$COMMIT_SHA',
      '--region',
      '${_REGION}',
      '--platform',
      'managed',
      '--quiet',
      '--allow-unauthenticated'
    ]
options:
  logging: CLOUD_LOGGING_ONLY
